name: Keep Render Service Warm

on:
  schedule:
    # every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl the health endpoint
        run: |
          curl -s https://nutrition-3tz6.onrender.com/healthz > /dev/null